#!/bin/sh

doit(){
  local X="$(find .. * .* -mindepth 0 -maxdepth 0 -exec sdmenu .. {} +)"
  [ -z "$X" ] && echo "cd '$PWD'" && return
  [ ! -d "$X" ] && echo "xdg-open '$PWD/$X'" && return
  cd "$X"
  doit
}

eval "$(doit)"
